# capsule version
version = "0.10.4"

deployment = "deployment.toml"

[[contracts]]
name = "eth-bridge-lockscript"
template_type = "Rust"

[[contracts]]
name = "eth-bridge-typescript"
template_type = "Rust"
