[workspace]
members = [
    "tests",
    "contracts/eth-bridge-lockscript",
    "contracts/eth-bridge-typescript"
]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
panic = 'abort'